version: "3.8"

services:

  ltl_api:
    build:
      context: ../API
      dockerfile: api.dockerfile
    container_name: SelfPage
    depends_on:
      - nginx
    env_file:
      - .env
    ports:
      - "8023:8000"
    volumes:
      - ../API:/LittleAPI
    command: python3 main.py
    networks:
      - ltl_net

  nginx:
    image: 'nginxproxy/nginx-proxy:latest'
    container_name: 'nginx-proxy'
    volumes:
      - 'html:/usr/share/nginx/html'
      - 'dhparam:/etc/nginx/dhparam'
      - 'vhost:/etc/nginx/vhost.d'
      - 'certs:/etc/nginx/certs'
      - 'conf:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: 'always'
    networks:
      - ltl_net
    ports:
      - '80:80'
      - '443:443'

  acme:
    image: 'nginxproxy/acme-companion:latest'
    container_name: 'nginx-proxy-acme-companion'
    depends_on:
      - 'nginx'
    volumes_from:
      - 'nginx'
    volumes:
      - 'acme:/etc/acme.sh'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      NGINX_PROXY_CONTAINER: 'nginx-proxy'
      DEFAULT_EMAIL: 'neveric@protonmail.com'
    restart: 'always'
    networks:
      - ltl_net
    env_file:
      - .env

volumes:
  html:
  dhparam:
  vhost:
  certs:
  conf:
  acme:

networks:
  ltl_net:
    driver: bridge