version: "3.8"

services:

  ltl_api:
    build:
      context: ../API
      dockerfile: api.dockerfile
    container_name: SelfPage
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "8023:8000"
    volumes:
      - ../API:/LittleAPI
    command: python3 main.py
